# Sample workflow for building and deploying a Next.js site to AWS Lambda
#
# To get started with Next.js see: https://nextjs.org/docs/getting-started
#
name: Deploy Next.js site to AWS Lambda

on:
  push:
    branches: ['main']
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

concurrency:
  group: 'lambda-deploy'
  cancel-in-progress: false

jobs:
  build:
    name: Build Nextjs Proj
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: yarn
      - name: Install dependencies
        run: yarn install
      - name: Build project
        run: yarn build
      - name: Serverless deployment
        uses: serverless/github-action@master
        with:
          args: deploy --config serverless-next.yml
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'
